### ISSUE TITLE
The translation of "provider" in Chinese documents is somewhat ambiguous in meaning

### ISSUE THREAD

**Issue by ZhongGuangshen** [twinnydotdev/twinny-docs#9]
In Chinese documents, 'provider' is directly translated as' 提供商', meaning the person who provides something, but this can cause some ambiguity when reading because readers cannot intuitively understand what service you are providing. Would it be better to translate' provider 'as' 接口提供者'? which means that it provides an interface for the Twinny extension AI service and we can easily understand the role it's playing.

**Comment by ZhongGuangshen** [comment]
This is about #8

**Comment by yuzcat01** [comment]
Thank you for your correction! I apologize if I made an inappropriate translation. But did you perhaps confuse "inference" and "interface"? I couldn't find an official translation for "Inference providers", so I had to do a direct translation. Inference providers are components in machine learning and artificial intelligence systems that are responsible for executing model inference (inference).However, it does provide interfaces so that other systems or applications can call it. If possible, we can discuss this further.

**Comment by fishshi** [comment]
https://github.com/twinnydotdev/twinny-docs/blob/4e97655ce33cf3105a0abda654d255fe2a004b3a/astro.config.mjs#L31-L35
`提供商` is indeed an inappropriate translation, but IMO, `推理提供者` would be a more appropriate translation than `接口提供者` because `providers` refers to `Inference providers`. In addition, while `接口` refers to a design-level concept, `推理` pertains to a service or functional level, which is more user-friendly for the latter.

**Comment by ZhongGuangshen** [comment]
> https://github.com/twinnydotdev/twinny-docs/blob/4e97655ce33cf3105a0abda654d255fe2a004b3a/astro.config.mjs#L31-L35
> 
> 
> `提供商` is indeed an inappropriate translation, but IMO, `推理提供者` would be a more appropriate translation than `接口提供者` because `providers` refers to `Inference providers`. In addition, while `接口` refers to a design-level concept, `推理` pertains to a service or functional level, which is more user-friendly for the latter.

It's reasonable, but I still feel that "接口提供者/接口提供商"" is more common than "推理提供者/推理提供商" on Chinese Internet. Translated as "接口", it may be easier for users to understand its role quickly. After all, when learning the LLM engines and models, the concept of “接口” would be contacted much more than the concept of  “推理”
